### ISSUE TITLE
MacOS Compile Error

### ISSUE THREAD

**Issue by zhmrab** [forknote/forknote#110]
Some issues with code mainly regarding MacOS 

```
/src/crypto/slow-hash.cpp:70:7: error: '~cn_context' has a non-throwing exception specification but can still throw [-Werror,-Wexceptions]
      throw bad_alloc();
      ^
/Users/zhmrab/fork/src/crypto/slow-hash.cpp:68:15: note: destructor has a implicit non-throwing exception specification
  cn_context::~cn_context() {
              ^
1 error generated.
make[3]: *** [src/CMakeFiles/Crypto.dir/crypto/slow-hash.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....

```

**Comment by pmitchev** [comment]
Got the same error after updating to 10.13.4

**Comment by Remco75** [comment]
Same issue here after updating . Any known fix yet?

**Comment by Remco75** [comment]
This also happens in cryptonote repo. Seems to be related to update to C++ or xcode.

filed an issue there as well:
https://github.com/cryptonotefoundation/cryptonote/issues/253
